name: Alerting Release tests workflow in Bundled OpenSearch Dashboards
on:
  pull_request:
    branches: [ '**' ]

jobs:
  tests:
    uses: ./.github/workflows/release-e2e-workflow-template.yml
    with:
      test-name: Alerting
      test-command: env CYPRESS_NO_COMMAND_LOG=1 yarn cypress:run-with-security --browser chromium --spec 'cypress/integration/plugins/alerting-dashboards-plugin/*'
      multi-opensearch-enabled: false
