name: Assistant Release tests workflow in Bundled OpenSearch Dashboards
on:
  pull_request:
    branches: ['**']
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.filter.outputs.tests }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            tests:
              - 'cypress/**/dashboards-assistant/**'
              - 'cypress/support/assistant-dummy-llm.js'

  tests-with-security:
    needs: changes
    if: ${{ needs.changes.outputs.tests == 'true' }}
    uses: ./.github/workflows/release-e2e-workflow-template.yml
    with:
      test-name: dashboards assistant
      test-command: env CYPRESS_DASHBOARDS_ASSISTANT_ENABLED=true yarn cypress:run-with-security --browser chromium --spec 'cypress/integration/plugins/dashboards-assistant/*'
      osd-serve-args: --assistant.chat.enabled=true
      artifact-name-suffix: "-with-security"
  
  tests-without-security:
    needs: changes
    if: ${{ needs.changes.outputs.tests == 'true' }}
    uses: ./.github/workflows/release-e2e-workflow-template.yml
    with:
      test-name: dashboards assistant
      test-command: env CYPRESS_DASHBOARDS_ASSISTANT_ENABLED=true yarn cypress:run-without-security --browser chromium --spec 'cypress/integration/plugins/dashboards-assistant/*'
      osd-serve-args: --assistant.chat.enabled=true
      security-enabled: false
      artifact-name-suffix: "-without-security"
  tests-with-multiple-data-source-and-disabled-local-cluster:
    needs: changes
    if: ${{ needs.changes.outputs.tests == 'true' }}
    uses: ./.github/workflows/release-e2e-workflow-template.yml
    with:
      test-name: dashboards assistant
      test-command: env CYPRESS_DISABLE_LOCAL_CLUSTER=true CYPRESS_DATASOURCE_MANAGEMENT_ENABLED=true CYPRESS_DASHBOARDS_ASSISTANT_ENABLED=true yarn cypress:run-with-security --browser chromium --spec 'cypress/integration/plugins/dashboards-assistant/mds*.js'
      osd-serve-args: --data_source.enabled=true --data_source.ssl.verificationMode=none --data_source.hideLocalCluster=true --assistant.chat.enabled=true
      security-enabled: true
      artifact-name-suffix: "-with-security-and-mds"

