name: Bundle Snapshot based E2E Cypress tests workflow for core Dashboards (Windows)
on:
  pull_request:
    branches: [ '**' ]
    paths:
      - 'cypress/**/core-opensearch-dashboards/**'
      - 'cypress/utils/dashboards/**'
  push:
    branches: [ '**' ]
    paths:
      - 'cypress/**/core-opensearch-dashboards/**'
      - 'cypress/utils/dashboards/**'

jobs:
  tests-with-security:
    uses: ./.github/workflows/release-e2e-workflow-template-windows.yml
    with:
      test-name: Core Dashboards using Bundle Snapshot
      test-command: env CYPRESS_NO_COMMAND_LOG=1 CYPRESS_VISBUILDER_ENABLED=true CYPRESS_DATASOURCE_MANAGEMENT_ENABLED=true CYPRESS_BANNER_ENABLED=true yarn cypress:run-with-security --browser chrome --spec 'cypress/integration/core-opensearch-dashboards/opensearch-dashboards/**/*.js'
      # not useful now as the windows e2e template currently do not allow serving parameters
      #osd-serve-args: --data_source.enabled=true --vis_builder.enabled=true

  tests-without-security:
    uses: ./.github/workflows/release-e2e-workflow-template-windows.yml
    with:
      test-name: Core Dashboards using Bundle Snapshot
      test-command: env CYPRESS_NO_COMMAND_LOG=1 CYPRESS_VISBUILDER_ENABLED=true CYPRESS_DATASOURCE_MANAGEMENT_ENABLED=true CYPRESS_BANNER_ENABLED=true yarn cypress:run-without-security --browser chrome --spec 'cypress/integration/core-opensearch-dashboards/opensearch-dashboards/**/*.js'
      # not useful now as the windows e2e template currently do not allow serving parameters
      #osd-serve-args: --data_source.enabled=true --vis_builder.enabled=true
      security-enabled: false
